### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by luxysiv** [tanishqmanuja/apkmirror-downloader#1]
Not sure but when I used your script, has a warning
```node:internal/process/task_queues:95
    runMicrotasks();
    ^

TypeError: undefined is not a function
    at zl (/snapshot/bin/apkmd.cjs)
    at /snapshot/bin/apkmd.cjs
    at <anonymous>
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)```

**Comment by tanishqmanuja** [comment]
Can you provide more context for example,

OS: Window 11 x64

Used config:
```
{
  "options": {
    "arch": "arm64-v8a"
  },
  "apps": [
    {
      "name": "yt",
      "org": "google-inc",
      "repo": "youtube",
      "version": "18.40.34"
    }
  ]
}
```

Other stuff like:
- Method of Executing the apkmd.exe, drag and dropped config file over exe or used command prompt?

**Comment by luxysiv** [comment]
I used command prompt. 
![Screenshot_2023-12-29-19-51-51-434_com kiwibrowser browser-edit](https://github.com/tanishqmanuja/apkmirror-downloader/assets/46205571/9798bbd7-cd82-48a3-ad00-6e27975a8f6f)
And I try to build to run on linux
This is command
```cat <<EOF > app.json
{
  "options": {
    "arch": "arm64-v8a"
  },
  "apps": [
    {
      "name": "yt",
      "org": "google-inc",
      "repo": "youtube",
      "version": "$version"
    }
  ]
}
EOF

chmod +x apkmd && ./apkmd app.json```

**Comment by tanishqmanuja** [comment]
Thanks for the issue, fixed :)
