### ISSUE TITLE
DPI option

### ISSUE THREAD

**Issue by Sp3EdeR** [tanishqmanuja/apkmirror-downloader#10]
It could be a useful option to allow filtering downloads per DPI. Some apps have multiple versions of the same arch on APKMirror, but with a different DPI.

**Comment by tanishqmanuja** [comment]
Done

**Comment by Sp3EdeR** [comment]
I cannot find any documentation on the DPI option in the README.md currently.

**Comment by Sp3EdeR** [comment]
Awesome, thank you!
