### ISSUE TITLE
Filter by minimum api version

### ISSUE THREAD

**Issue by TheUnityGuy** [tanishqmanuja/apkmirror-downloader#16]
I think it would be a neat feature while looking for a package for slightly older devices :)

**Comment by tanishqmanuja** [comment]
Nice idea 💯

**Comment by tanishqmanuja** [comment]
Although I have added a filter for minAndroidVersion, but still the process would have to be manual because not many apk variants have multiple supported android versions nowadays. For example YT Music only has 8.0+ for all variants.

**Comment by TheUnityGuy** [comment]
A solution for this might be converting that 8.0+ tag to the actual API version and comparing that number to version selected by user. At least I think so 😅. Thank you for such rapid response btw.

**Comment by tanishqmanuja** [comment]
Do you mean mapping the android version to the sdk version ? Like Android 15 -> API 35 etc etc. For now i guess the simple logic is best for making the scrapping easier.

**Comment by TheUnityGuy** [comment]
Yeah something exactly like that. Simpler logic surely is better especially for scraping, but maybe as the project is entirely in typescript you can add interfaces to make sure the data is scraped correctly and then apply the filters. Just a suggestion to make the project easier to maintain for future features 😉.

**Comment by tanishqmanuja** [comment]
Sure, will definitely look into this.
