### ISSUE TITLE
Naming Issue

### ISSUE THREAD

**Issue by ddubnyk** [tanishqmanuja/apkmirror-downloader#21]
I've found another issue when downloading certain apps.  This one is how the download gets named.

Steam is an example of one of these.

Here is my json file.

`{
  "options": {
    "outDir": "/home/username/path/repo",
    "type": "apk",
    "overwrite": false
  },
  "apps": [
    {
      "org": "ookla",
      "repo": "speedtest",
      "arch": "arm64-v8a"
    },
    {
      "org": "valve-corporation",
      "repo": "steam"
    }
  ]
}`

If I download this manually, the file is named:
com.valvesoftware.android.steam.community_3.9.3-9305784_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk

However with the script it downloads as:
com.valvesoftware.android.steam.community_3.9.3-9305784_minAPI23(arm64-v8a%2Carmeabi-v7a%2Cx86%2Cx86_64)(nodpi)_apkmirror.com.apk

This seems to cause issues with Fdroid repos in particular in my case.  Leaving it as the original name, Fdroid has no problem with the APK, however with the way it gets renamed via the script it won't allow clients to download it.  It seems as if the "," is getting replaced with "%2C".

**Comment by tanishqmanuja** [comment]
Thanks for the issue 💯

Should be fixed with (e927493fafcba668850d234e95fb6ffa70647edc) in [release v2.0.8](https://github.com/tanishqmanuja/apkmirror-downloader/releases/tag/v2.0.8) .
