### ISSUE TITLE
Youtube downloading issue

### ISSUE THREAD

**Issue by Sp3EdeR** [tanishqmanuja/apkmirror-downloader#23]
Hello,

I seem to have found a new issue. When trying to download using either of the following configs:

```json
{"apps": [{"outFile": "Youtube 19.44.39", "org": "google-inc", "repo": "youtube", "arch": "universal", "dpi": "nodpi", "version": "19.44.39"}]}
```
```json
{"apps": [{"outFile": "Youtube 19.44.39", "org": "google-inc", "repo": "youtube", "arch": "arm64-v8a", "dpi": "nodpi", "version": "19.44.39"}]}
```

I receive the following output:

```
 *** APKMD (APKMirror Downloader) v2.0.8 ***

Downloading youtube 19.44.39...
Unable to download google-inc/youtube
Could not find final download url
```

Using the following configuration still works fine, so I assume the error message is not quite right:

```json
{"apps": [{"outFile": "Youtube 19.16.39", "org": "google-inc", "repo": "youtube", "arch": "arm64-v8a", "dpi": "nodpi", "version": "19.16.39"}]}
```

Help would be greatly appreciated :)

**Comment by tanishqmanuja** [comment]
### For config 1
![image](https://github.com/user-attachments/assets/39358897-1079-4ffc-87b3-cfba2b78f17b)

### For config 2
![image](https://github.com/user-attachments/assets/7d2669d5-b354-4e6e-8034-9e75f9a2d1fc)

Both work for me, maybe something else is wrong. Could be a cloudflare thing also .. have you tried with different IP or network connection ?

**Comment by Sp3EdeR** [comment]
Thanks for your help, it worked now from the same computer with the same connection. It is just very strange that one version was stably working and another not at all. I guess it was due to some kind of a Cloudflare cache mechanism. Sorry for the false report!
