### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by luxysiv** [tanishqmanuja/apkmirror-downloader#3]
Version 1.0.2 not download anymore
```APKMirror Downloader v1.0.2
- Downloading 1 apps
✖ Failed to download google-inc/youtube@18.45.43
✔ Downloaded [1/1] apps

**Comment by luxysiv** [comment]
Maybe they put CF protection

**Comment by tanishqmanuja** [comment]
Yeah possibly, I also got 403 response while testing. If you send multiple requests within short time frame. It presents Bot Protection page which is hard to bypass via code for obvious reasons.

**Comment by luxysiv** [comment]
Problem with only YouTube

**Comment by tanishqmanuja** [comment]
I dont think, It happens for apps with large size (~over 100Mb) randomly when sending. Fixes itself after waiting for sometime.. mostly a rate limit implemented using CF

**Comment by luxysiv** [comment]
Now works again

**Comment by luxysiv** [comment]
Thanks for your work

**Comment by luxysiv** [comment]
Can you add by pass DDOS CF to your script ?

**Comment by tanishqmanuja** [comment]
What is DDOS CF ? If that's like a FOSS and easy to add to the project then sure. Most other Cloudflare bypass methods are subscription based and require payment.

**Comment by luxysiv** [comment]
Oh, thanks
