### ISSUE TITLE
getting only alpha versions from apkmirror versions

### ISSUE THREAD

**Issue by mamiiblt** [tanishqmanuja/apkmirror-downloader#5]
Hello, i have an automation project. Each version obtained from apkmd (akpmd decides that the versions are the latest version according to the upload date on apkmirror) may not actually be the most up-to-date build. How can I check in my own code that this is the latest version?

The app i want to get the latest version of is instagram (latest version is 315.0.0.0.20 alpha)
Is it possible to make a setting accordingly while downloading the application in apkmd?

![image](https://github.com/tanishqmanuja/apkmirror-downloader/assets/70213359/d5344620-c0fd-46b0-a365-71129e524ff4)

**Comment by tanishqmanuja** [comment]
Yeah, it should be possible.. here is the line you would be interested in

https://github.com/tanishqmanuja/apkmirror-downloader/blob/main/src%2Fscrapping.ts#L49

Current apkmd gets the first item in the table.

What you could do is scan the entire table parsing the version from each item and let the highest parser version be the latest version.

Although I don't know what kind of automation you're doing. But keep in mind APK Mirror has a 
Cloudflare IP ban system if you send requests to APK Mirror too quickly or frequently.
