### ISSUE TITLE
Version extraction does not work for weird Twitter version numbering

### ISSUE THREAD

**Issue by ponces** [tanishqmanuja/apkmirror-downloader#7]
Title is self-explanatory.
Twitter version numbering is something like `x.x.x-release.x` so the last part is taken out during version extraction which makes download to fail.
Can this be considered for Twitter? I can push a PR if you prefer but most likely you do this easy-peasy by considering a different regex :P
Thanks!

**Comment by tanishqmanuja** [comment]
Honestly, I would appreciate a PR, my guess is something like '\b\d+(\.\d+)+(-\S+)?' should do. Can you test and PR?

**Comment by tanishqmanuja** [comment]
fixed in commit 8a8be4b57ffee7e45a904a5d922fa525d09d482a

**Comment by tanishqmanuja** [comment]
@ponces, that should be due to latest version being a beta and not having a APK release (it only has a bundle)

**Comment by ponces** [comment]
You're right!
Can't we just ignore `alpha` and `beta` tagged releases?
I can push an update on that later today if you agree...

**Comment by tanishqmanuja** [comment]
That's exactly what i did for now. But it looks a little bit hacky, I personally use apkmd for downloading a particular version of youtube and youtube-music apks, then generating revanced apps. Thus the hacky solution doesn't bother me enough to implement something better.

But if you implement something better, I will be happy to accept your PR :)

**Comment by ponces** [comment]
Well... My usage is exactly the same but I generate revanced apps for latest version apps ideally :P
That's why I need that Twitter latest stable version :)
Let me check if your change suits my needs! Thank you very much!!

**Comment by ponces** [comment]
It's perfectly working! Thanks!
