### ISSUE TITLE
Architecture options

### ISSUE THREAD

**Issue by Sp3EdeR** [tanishqmanuja/apkmirror-downloader#9]
Hello!

Currently the options/arch can contain just one architecture value. It would be a helpful feature for arch to accept a list of values, such as: ["arm64-v8a", "universal", "noarch"], and the app would download the first one found.

**Comment by tanishqmanuja** [comment]
Now the downloader will fallback to `universal` if selected arch is not found, `universal` and `noarch` are now interchangeable.

**Comment by Sp3EdeR** [comment]
Awesome! Thanks! :)
